dist: xenial
sudo: false
language: go

services:
  - redis-server

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

go_import_path: github.com/shareed2k/go_limiter

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
